# Generated by Django 3.2.13 on 2022-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
